---
- name: install haproxy
  apt:
    name: haproxy
    state: present
- name: copy haproxy cert
  copy:
    dest: /var/lib/jenkins/
    src: files/jenkins.pem
- name: copy the haproxy config
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart haproxy service
  systemd:
    state: restarted
    name: haproxy
