- name: Add Poshbot Module
  win_psmodule:
    name: PoshBot
    state: present
- name: Create Poshbot Directory
  win_file:
    path: '{{ item }}'
    state: Directory
  with_items:
    - 'c:\poshbot'
    - 'c:\poshbot\plugins'
    - 'c:\poshbot\logs'
- name: Copy config template
  template:
    src: templates/config.j2
    dest: 'c:\poshbot\config.psd1'
- name: Copy roles template
  template:
    src: templates/roles.j2
    dest: 'c:\poshbot\roles.psd1'
- name: Copy roles groups
  template:
    src: templates/groups.j2
    dest: 'c:\poshbot\groups.psd1'
- name: Copy permissions template
  template:
    src: templates/permissions.j2
    dest: 'c:\poshbot\permissions.psd1'
- name: copy start poshbot script
  win_copy:
    src: files/Start-Poshbot.ps1
    dest: 'C:\poshbot\Start-Poshbot.ps1'