---
- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true
- name: waiting 60 secs for server to come back
  become: false
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    state: started
    delay: 60
    timeout: 120
  delegate_to: localhost