---
- name: Set timezone to 'GMT Standard Time' (GMT)
  win_timezone:
    timezone: GMT Standard Time
- name: Set region to en-GB
  win_region:
    location: 242
    unicode_language: en-GB
    format: en-GB
    copy_settings: True
  notify: restart server