---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
- name: install the latest version of nginx
  yum:
    name: nginx
    state: present
- name: add index file
  template:
    src: templates/index.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'
- name: run nginx
  service:
    name: nginx
    state: started