---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: percygrunwald/docker-ubuntu1804-ansible
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
