---
- name: ensure bind and bind-utils are installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - bind
    - bind-utils
- name: start bind
  service:
    name: named
    state: started
