---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  register: server_update
- name: Reboot the server
  shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  when: server_update is changed
- name: Wait for server to restart
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    state: started
    delay: 60
    timeout: 120
  delegate_to: localhost
  vars:
    ansible_become: no
  when: server_update is changed
