---
- name: Update and upgrade apt packages.
  apt:
    upgrade: yes
    update_cache: yes
  register: server_update

- name: Reboot the server.
  reboot:
    reboot_timeout: 3600
  when: server_update is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: server_update is changed
