---
- name:
  win_domain:
    dns_domain_name: '{{ domain_name }}'
    safe_mode_password: '{{ safe_mode_password }}'
  notify: restart server
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present
- name: Install DNS SubFeature
  win_feature:
    name: DNS
    include_sub_features: true
    include_management_tools: true
    state: present
  notify: restart server
