---
- name: "Get distribution"
  get_url:
    url: "http://download.jetbrains.com/teamcity/TeamCity-{{ teamcity_server_version }}.tar.gz"
    dest: "/tmp/TeamCity-{{ teamcity_server_version }}.tar.gz"
    validate_certs: no
    timeout: 60
    checksum: "sha256:{{ teamcity_server_sha256 }}"
  register: _teamcity_package

- name: Ensure Java 8 is installed.
  package:
    name: "java-1.8.0-openjdk"
    state: present

- name: Set JAVA_HOME
  copy:
    src: java_home.sh
    dest: /etc/profile.d/java_home.sh
    mode: 0644

# directories

- name: "Unpack distribution"
  unarchive:
    src: "/tmp/TeamCity-{{ teamcity_server_version }}.tar.gz"
    dest: "{{ teamcity_server_install_dir }}"
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    copy: "no"

# user
- name: "Create teamcity group"
  group:
    name: "{{ teamcity_server_group }}"
    state: present
    system: yes

- name: "Create teamcity user"
  user:
    name: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    state: present
    shell: /bin/bash
    createhome: yes
    system: yes
    home: "{{ teamcity_server_home }}"