---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "vagrant/**"
      - "ansible-kitchen/**"
      - ".vscode/**"

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule docker yamllint ansible-lint

      - name: Yaml lint playbooks and roles
        run: yamllint .

      - name: Run Ansible lint
        run: ansible-lint *.yml
